### ISSUE TITLE
Create  renderLicenseBadge function

### ISSUE THREAD

**Issue by MsPickles1014** [MsPickles1014/challenge-5#8]
Create a function that returns a license badge based on which license is passed in.
If there is no license, return an empty string

**Comment by MsPickles1014** [comment]
completed

**Comment by jjyutm4532** [comment]
Hello, I tried to solve the issue.

This is what I did:

Modified the renderLicenseBadge function to return an empty string when no license is provided or when the license is 'None'. This change satisfies the criteria of returning an empty string if there is no license.

You can review changes in this commit: https://github.com/jjyutm4532/MsPickles1014-challenge-5-8/commit/a461e8c181087c136b4b1265ccde513f3f428d54.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
